swagger: "2.0"
info:
  version: "0.0.1"
  title: "Node Js Projects"
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /clubhouse
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /drinks:
    # binds a127 app logic to a route
    x-swagger-router-controller: drinkController
    get:
      description: Returns a array of drinks
      # used as the method name of the controller
      operationId: getAll
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/InfoResponse"
            # a pointer to a definition
            # $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /player/_create:
    # binds a127 app logic to a route
    x-swagger-router-controller: playerController
    post:
      description: Returns a player
      # used as the method name of the controller
      operationId: create
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/InfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /player/{player}:
    # binds a127 app logic to a route
    x-swagger-router-controller: playerController
    get:
      description: Returns a player
      # used as the method name of the controller
      operationId: getById
      parameters:
        - in: path
          name: player
          required: true
          type: string
          minimum: 1
          description: The player ID.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/InfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /player/{player}/_password:
    # binds a127 app logic to a route
    x-swagger-router-controller: playerController
    put:
      description: Returns a player
      # used as the method name of the controller
      operationId: updatePassword
      parameters:
        - in: path
          name: player
          required: true
          type: string
          minimum: 1
          description: The player ID.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/InfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Returns a player
      # used as the method name of the controller
      operationId: updateBill
      parameters:
        - in: path
          name: player
          required: true
          type: string
          minimum: 1
          description: The player ID.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/InfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /player/{player}/drinks:
    # binds a127 app logic to a route
    x-swagger-router-controller: playerController
    delete:
      description: Returns a player
      # used as the method name of the controller
      operationId: deleteBill
      parameters:
        - in: path
          name: player
          required: true
          type: string
          minimum: 1
          description: The player ID.
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/InfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  InfoResponse:
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
